# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true

summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"
[params]
Description = "Bernard Lodge #225 Listowel, Ontario Free Masonry, FreeMasons, Ancient Free and Accepted Masonry, Freemasonry, Listowel"
keywords = ["Freemasonry", "Masonic Lodge", "Bernard Lodge", "Listowel", "Ontario", "Free Masonry", "Ancient Free and Accepted Masonry", "Lodge 225"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[pagination]
pagerSize = 5

[imaging]
anchor = 'smart'
resampleFilter = "Lanczos"


[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.8

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]
page = ["HTML"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "series"
weight = 50

[[related.indices]]
name = "authors"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = false
name = 'fragmentrefs'
type = 'fragments'
weight = 10
